package org.ulithi.jlisp.parser;

import org.ulithi.jlisp.exception.ParseException;

import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * The {@link Lexer} forms LISP language tokens from an {@link InputStream} or a {@link String} of
 * characters representing a LISP program or expression to be evaluated.
 * <p>
 * Aside from basic tokenization, the {@code Lexer} also handles expansion of the single-quote ( ' )
 * shorthand for the QUOTE function: e.g., transforms 'A in the input to "(", "QUOTE", "A", ")" in
 * the generated list of tokens.
 * <p>
 * I originally tried to do this in the {@link Parser}, but that proved more challenging since it
 * involves some amount of look-ahead to determine what is being quoted. It's easier to do here
 * than to deal with the complexity of the {@code SExpression} that is generated by the parser.
 */
public class Lexer {

    /**
     * To handle multi-line inputs, the lexer can accept a series of inputs (i.e. partially complete
     * forms), maintain scanning state across them, and indicate when a full form has been input
     * and is ready for parsing.
     */
    private static class State {
        /** The ordered list of tokens produced by lexical analysis. */
        final List<Token> tokens = new ArrayList<>();

        int depth = 0;               // Parenthesis depth of all tokenized input.
        boolean inQuote = false;     // Are we processing quoted (') input?
        int quoteDepth = 0;          // Parenthesis depth of quoted (') input.
        boolean expectAtom = false;  // Whether we expect the quoted (') input to be an atom.
        boolean inComment = false;   // Are we processing commented-out input?

        private boolean isComplete() {
            return depth == 0 && !tokens.isEmpty();
        }
    }

    /** Scanning state for the form/input currently being processed. */
    private State state;

    /**
     * Constructs a new Lexer instance.
     */
    public Lexer() {
         state = new State();
    }

    /**
     * Reads the given {@link InputStream} stream as a string of characters and tokenizes it.
     * @param stream An input stream.
     */
    public void append(final InputStream stream) throws IOException {
        final byte[] bytes = new byte[1024];
        final StringBuilder text = new StringBuilder();

        while (stream.available() > 0 && stream.read(bytes, 0, 1024) > 0) {
            text.append(new String(bytes).trim().toUpperCase());
            Arrays.fill(bytes, (byte) 0);
        }

        append(text.toString());
    }

    /**
     * Reads the given string and tokenizes it.
     * @param s A string of LISP program text.
     */
    public void append(final String s) {
        try {
            tokenize(s, state);
        } catch (final ParseException e) {
            reset();
            throw e;
        }
    }

    /**
     * Resets this {@link Lexer} by clearing its accumulated list of tokens and related scanning
     * state.
     */
    public void reset() {
        state = new State();
    }

    /**
     * Indicates if the form currently being processed is a complete (but not necessarily
     * syntactically correct) form.
     */
    public boolean isComplete() {
        return state.isComplete();
    }

    /**
     * Returns the tokens formed from the stream or string by this {@link Lexer}.
     *
     * @return An ordered list of tokens.
     */
    public List<Token> getTokens() {
        return Collections.unmodifiableList(state.tokens);
    }

    /**
     * Indicates if this {@link Lexer} has tokens parsed and available.
     * @return True if this {@code Lexer} has tokens parsed and available, false otherwise.
     */
    public boolean hasTokens() {
        return !state.tokens.isEmpty();
    }

    /**
     * Transforms a string into an ordered list of Lisp language tokens, based on the current
     * state of the lexer. The lexer state is updated by this method as the input is being
     * scanned and processed.
     *
     * @param s A string representing (presumably) a Lisp language statement or program.
     * @param state Represents the current state of the lexer, including tokens scanned for the
     *              expression currently being processed, quote state and so on.
     */
    private static void tokenize(final String s, final State state) {
        final List<Token> tokens = new ArrayList<>();
        int i = 0;

        while (i < s.length()) {
            int j = i + 1;
            final char ch = s.charAt(i);

            if (ch == Grammar.EOL) {
                state.inComment = false;
            } else if (state.inComment) {
                // Continue
            } else if (ch == Grammar.SEMI) {
                state.inComment = true;
            } else if (ch == Grammar.QUOTE && !state.inQuote) {
                tokens.add(Token.LPAREN);
                tokens.add(Token.asSymbol("QUOTE"));
                state.inQuote = true;
                state.expectAtom = true;
            } else if (isIdentifierStart(ch) || isNumericLiteralStart(ch)) {
                boolean isNumericLiteral = isNumericLiteralStart(ch);
                while (j < s.length() && Grammar.IDENTIFIER_REST_PATTERN.matcher(s.substring(i, j + 1)).matches()) {
                    j++;
                }

                tokens.add(isNumericLiteral ? Token.asLiteral(s.substring(i, j)) : Token.asSymbol(s.substring(i, j)));

                if (state.expectAtom) {
                    tokens.add(Token.RPAREN);
                    state.inQuote = false;
                    state.expectAtom = false;
                }
            } else if (ch == Grammar.LPAREN_CHAR) {
                state.expectAtom = false;
                if (state.inQuote) {
                    state.quoteDepth++;
                } else {
                    state.depth++;
                }
                tokens.add(Token.LPAREN);
            } else if (ch == Grammar.RPAREN_CHAR) {
                if (state.inQuote) {
                    state.quoteDepth--;
                    if (state.quoteDepth == 0) {
                        tokens.add(Token.RPAREN);
                        state.inQuote = false;
                    }
                } else {
                    state.depth--;
                }
                tokens.add(Token.RPAREN);
            } else if (ch == Grammar.DOUBLE_QUOTE) {
                final StringBuilder stringContent = new StringBuilder();

                while (j < s.length()) {
                    if (s.charAt(j) == '\\') {
                        // Handle escape sequence
                        if (j + 1 < s.length()) {
                            final char escaped = s.charAt(j + 1);
                            switch (escaped) {
                                case 'n': stringContent.append('\n'); break;
                                case 't': stringContent.append('\t'); break;
                                case 'r': stringContent.append('\r'); break;
                                case '\"': stringContent.append('"'); break;
                                case '\\': stringContent.append('\\'); break;
                                default: stringContent.append(escaped);
                            }
                            j += 2;
                        } else {
                            throw new ParseException("Incomplete escape sequence");
                        }
                    } else if (s.charAt(j) == '"') {
                        // End of string found
                        j++;
                        break;
                    } else {
                        stringContent.append(s.charAt(j));
                        j++;
                    }
                }

                if (j > s.length() || s.charAt(j - 1) != '"') {
                    throw new ParseException("Unterminated string literal");
                }

                // Create a string token with the processed content
                tokens.add(Token.asLiteral(stringContent.toString()));

                if (state.expectAtom) {
                    tokens.add(Token.RPAREN);
                    state.inQuote = false;
                    state.expectAtom = false;
                }
            } else if (isSymbol(ch)) {
                tokens.add(Token.asSymbol(String.valueOf(ch)));
            } else if (ch == Grammar.DOT_CHAR) {
                tokens.add(Token.DOT);
            }
            i = j;
        }

        // Too many closing parentheses is not salvageable.
        if (state.depth < 0) {
            throw new ParseException("Mismatched parentheses");
        }

        state.tokens.addAll(tokens);
        state.inComment = false;
    }

    private static boolean isIdentifierStart(final char ch) {
        return Grammar.IDENTIFIER_START_CHARS.contains(ch) || Character.isLetter(ch);
    }

    private static boolean isSymbol(final char ch) {
        return Grammar.SYMBOLS.contains(ch);
    }

    private static boolean isNumericLiteralStart(final char ch) {
        return Character.isDigit(ch) || ch == '-';
    }
}
