package org.ulithi.jlisp.parser;

import org.ulithi.jlisp.commons.CollectionUtils;
import org.ulithi.jlisp.core.Atom;
import org.ulithi.jlisp.core.List;
import org.ulithi.jlisp.core.SExpression;
import org.ulithi.jlisp.exception.ParseException;

import java.util.Optional;

import static org.ulithi.jlisp.parser.Grammar.NIL;

/**
 * Transforms an ordered list of tokens generated by the {@link Lexer} into an {@link SExpression},
 * which can then be evaluated as a LISP expression.
 */
public class Parser {

    /**
     * Parses and constructs an S-Expression for the LISP statements in the given list of tokens.
     * The actual parsing is done by a new instance of an inner class, to ensure parsing is
     * stateless (doesn't retain state between {@code parse} invocations.
     *
     * @param tokens An ordered list of LISP language tokens produced by lexical analysis of one
     *               or more LISP expressions.
     * @return An {@link SExpression} representing the forms presented in the list of tokens.
     */
    public Optional<SExpression> parse(final java.util.List<Token> tokens) {
        if (CollectionUtils.isEmpty(tokens)) {
            return Optional.empty();
        }

        return Optional.of(ParserImpl.parse(tokens));
    }

    /**
     * The actual parser implementation. A new instance of this class is instantiated for every
     * invocation of {@link Parser#parse(java.util.List)}, to ensure no persistent state is retained
     * between invocations.
     */
    private static final class ParserImpl {
        /** Parses the list of tokens and returns the corresponding S-Expression. */
        static SExpression parse(final java.util.List<Token> tokens) {
            final ParserImpl parser = new ParserImpl();
            return parser.parseTokens(tokens);
        }

        /** Index of the token currently being processed. */
        private int pos = 0;

        /**
         * Initiates the recursive parsing of a list of tokens into an S-Expression. If the first
         * token is an atom, simply parses the value and returns an Atom of the appropriate type.
         * If the first token is a left parenthesis (list-start), returns the recursively parsed
         * List (s-expression).
         */
        private SExpression parseTokens(final java.util.List<Token> tokens) {
            final Token token = tokens.get(pos);

            pos++;
            if (token.isListStart()) {
                return parseList(tokens);
            } else if (token.isNil()) {
                return Atom.NIL;
            } else if (token.isSymbol()) {
                return Atom.createSymbol(token.value());
            } else if (token.isLiteral()) {
                return parseToken(token.value());
            }
            pos--;

            throw new ParseException("Unexpected token: " + token);
        }

        /**
         * Parses and returns tokens representing a LISP list, as a List (s-expression).
         */
        private List parseList(final java.util.List<Token> tokens) {
            if (pos >= tokens.size()) {
                throw new ParseException("Mismatched parentheses");
            }

            // Handle empty list
            if (tokens.get(pos).isListEnd()) {
                pos++;
                return List.create();
            }

            // Parse car
            SExpression car = parseTokens(tokens);

            // Check for dot notation
            if (pos < tokens.size() && tokens.get(pos).isDot()) {
                pos++;
                SExpression cdr = parseTokens(tokens);

                if (pos >= tokens.size() || !tokens.get(pos).isListEnd()) {
                    throw new ParseException("Dotted pair should have exactly two sub-forms");
                }

                pos++;
                return List.create(car, cdr);
            }

            // Normal list
            org.ulithi.jlisp.core.List cdr = parseList(tokens);
            final org.ulithi.jlisp.core.List ret = org.ulithi.jlisp.core.List.create();
            ret.add(car);
            if (!cdr.isNil()) {
                ret.append(cdr);
            }
            return ret;
        }

        /**
         * Parses a single atomic token and returns the appropriate {@link Atom reference}.
         *
         * @param token The token to be parsed.
         * @return A numeric, string or symbolic {@link Atom} corresponding to the token, depending on
         * the detected data type of the token.
         */
        private static Atom parseToken(final String token) {
            if (NIL.equalsIgnoreCase(token)) { return Atom.NIL; }
            if (Grammar.isNumeric(token)) { return Atom.create(Integer.parseInt(token)); }
            return Atom.create(token);
        }
    }
}
