package org.ulithi.jlisp.parser;

import org.ulithi.jlisp.commons.CollectionUtils;
import org.ulithi.jlisp.exception.JLispRuntimeException;
import org.ulithi.jlisp.exception.ParseException;
import org.ulithi.jlisp.mem.Atom;
import org.ulithi.jlisp.mem.Cell;
import org.ulithi.jlisp.mem.PTree;

import java.util.ArrayList;
import java.util.List;
import java.util.Stack;

import static org.ulithi.jlisp.parser.Grammar.*;

/**
 * Transforms an ordered list of tokens generated by the {@link org.ulithi.jlisp.lexer.Lexer} into
 * a {@link org.ulithi.jlisp.mem.PTree}, which can then be evaluated as a LISP expression.
 */
public class Parser {
    /**
     * An ordered list of parse trees representing individual LISP expressions, ready for evaluation.
     */
    private final List<PTree> expressions = new ArrayList<>();

    /**
     * Parses and construct parse trees for the LISP statements in the given list of tokens. Parsed
     * expressions are appended to this parser's expressions list.
     *
     * @param tokens An ordered list of LISP language tokens produced by lexical analysis of one
     *               or more LISP expressions.
     */
    public PTree parse(final List<String> tokens) {
        if (CollectionUtils.isEmpty(tokens)) {
            throw new ParseException("Can't parse empty expression");
        }

        if (tokens.size() == 1) {
            final Atom atom = parseAtom(tokens.get(0));
            return new PTree(Cell.create(atom));
        }

        return parseList(tokens);
    }

    private PTree parseList(final List<String> tokens) {
        if (tokens == null) {
            throw new JLispRuntimeException("Unexpected null token list");
        }

        final Stack<PTree> stack = new Stack<>();
        PTree pTree = new PTree();
        boolean outer = true;

        for (final String token: tokens) {
            if (token.equals(LPAREN)) {
                if (!outer) {
                    stack.push(pTree);
                    pTree = new PTree();
                }
                outer = false;
            } else if (token.equals(RPAREN)) {
                if (!stack.empty()) {
                    final PTree newOne = pTree;
                    pTree = stack.pop();
                    pTree.addList(newOne.root());
                }
            } else {
                pTree.add(Cell.create(parseAtom(token)));
            }
        }

        return pTree;
    }

    /**
     * Parses a single atomic token and returns the appropriate {@link Atom} construct.
     * @param token The token to be parsed.
     * @return A numeric, string or symbolic {@link Atom} corresponding to the token,
     *         depending on the detected data type of the token.
     */
    private static Atom parseAtom(final String token) {
        if (Grammar.isNumeric(token)) {
            return Atom.create(Integer.parseInt(token));
        }

        // TODO Symbols, properly.
        if (token.equals("+") || token.equals("*")) {
            return Atom.createSymbol(token);
        }

        return Atom.create(token);
    }

    /**
     * This finds the closing parenthesis of a given Lisp segment
     *
     * @param tokens The tokens (in dot-notation) of a segment of Lisp code
     * @return the index of the closing parenthesis
     *
     * @throws IllegalArgumentException If the vector is not a parenthetical expression
     * @throws ArrayIndexOutOfBoundsException If the statement does not have a closing parenthesis
     *
     */
    private static int endOfExpression(final List<String> tokens) throws IllegalArgumentException, ArrayIndexOutOfBoundsException {

        if ( ! tokens.get(0).matches("[(]") ){
            throw new IllegalArgumentException("ERROR: Tried to find the end of an expression that did not begin with '('.");
        }

        int openPairs = 1;
        int end = 1;
        while (openPairs > 0) {
            if (end >= tokens.size()) {
                throw new ArrayIndexOutOfBoundsException("Error! Unbalanced parentheses.");
            }
            if (tokens.get(end).matches("[)]")) {
                openPairs--;
            } else if (tokens.get(end).matches("[(]")) {
                openPairs++;
            }
            if (openPairs == 0) {
                break;
            } else {
                end++;
            }
        }
        return end;
    }
}
